import { sql } from "drizzle-orm";
import {
  check,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { user } from "./auth.js";

// Application-owned workflow; never generated by Better Auth.
export const emailChangeRequest = pgTable(
  "email_change_request",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // Snapshot intentionally survives logout/session deletion. Never authenticates a caller.
    initiatingSessionId: text("initiating_session_id").notNull(),
    currentEmail: text("current_email").notNull(),
    newEmail: text("new_email").notNull(),
    status: text("status")
      .$type<
        | "pending_current_email"
        | "pending_new_email"
        | "completed"
        | "superseded"
      >()
      .notNull(),
    currentEmailTokenHash: text("current_email_token_hash"),
    newEmailTokenHash: text("new_email_token_hash"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
    currentEmailApprovedAt: timestamp("current_email_approved_at", {
      withTimezone: true,
    }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (t) => [
    uniqueIndex("email_change_active_user_idx")
      .on(t.userId)
      .where(
        sql`${t.status} in ('pending_current_email', 'pending_new_email')`,
      ),
    uniqueIndex("email_change_current_hash_idx").on(t.currentEmailTokenHash),
    uniqueIndex("email_change_new_hash_idx").on(t.newEmailTokenHash),
    check(
      "email_change_state_check",
      sql`(${t.status} = 'pending_current_email' and ${t.currentEmailTokenHash} is not null and ${t.newEmailTokenHash} is null) or (${t.status} = 'pending_new_email' and ${t.currentEmailTokenHash} is null and ${t.newEmailTokenHash} is not null) or (${t.status} in ('completed', 'superseded') and ${t.currentEmailTokenHash} is null and ${t.newEmailTokenHash} is null)`,
    ),
  ],
);
